# Getting Started

In [2]:
# Working from: http://scikit-learn.org/stable/modules/tree.html#classification

from sklearn import tree
X = [[0,0], [1,1]]
y = [0,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,y)

# A Tutorial

In [4]:
# Working from: http://scikit-learn.org/stable/tutorial/basic/tutorial.html#machine-learning-the-problem-setting

from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [5]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [6]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [8]:
digits.data[1]

array([ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
        9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
       15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
        0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
       16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.])

# Cross Validation

In [13]:
# Working from: http://scikit-learn.org/stable/modules/cross_validation.html

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

X = pd.read_csv('../../predsap/mlspace/mlspacetest_X.csv', sep=',')
y = pd.read_csv('../../predsap/mlspace/mlspacetest_y.csv', sep=',')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [20]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(3122, 5) (3122, 1)
(2082, 5) (2082, 1)


In [22]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth=4)
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
from sklearn.metrics import (accuracy_score, precision_score, 
                             recall_score, f1_score, log_loss)

clf.score(X_test, y_test)

0.9918347742555236

In [30]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X, y, cv=10)
print(scores)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.99040307 0.98080614 0.99616123 0.98848369 0.98269231 0.97692308
 0.98653846 0.99038462 0.98846154 0.98461538]
Accuracy: 0.99 (+/- 0.01)


# Now Apply

In [32]:
X2 = pd.read_csv('../../predsap/mlspace/mlspacetest_X2.csv', sep=',')
pred_df = pd.DataFrame(clf.predict(X2))

In [1]:
# pred_df.to_stata('../../predsap/mlspace/mlspacetest_X2.dta')